### ISSUE TITLE
Implement POM backend

### ISSUE THREAD

**Issue by amznpurple** [awslabs/yesiscan#10]
Here is a description of the new `pom` backend...

# Intro:

Many java projects contain "pom" files. They are small xml metadata files that often contain a license field. Reference here: https://maven.apache.org/pom.html#Licenses

We want to look for these files, parse them, and when they have license information, return that so that it can be aggregated with the data from the other backends.

# Design:

Please think about any design considerations you might have when working on this code. It is important to _think_ about what you're going to build before you code it. Always do it this way, as it helps avoid re-writing things you could have solved earlier.

# Code:

You'll probably want to implement a `Pom` struct. This will be a backend in the backend/ folder. It will probably look similar to the spdx.go backend in many ways. You might want to use that as a template.

The `Pom` struct will need to be included in lib/main.go where the other backends are pulled in.

You should add an example file in examples/<something>.pom that shows how this works.

# Testing:

If there is a reasonable type of test to write, please describe what kind of test you would write. Describe the details here before implementing them.

# Questions:

Any questions you have please add them to this issue. When you have something minimally viable, please send a pull request to this repo and link it in this issue. We will track your progress publicly here.

# Timeline:

A hacker experienced with `golang` and also with the `yesiscan` code base could probably implement this within 2 hours. An intermediate golang programmer could probably implement this within a day. Someone with some past experience coding but otherwise a beginner should be able to implement this within 2-3 days. If you feel you are blocked for more than 2-3 hours on any one aspect of this, please reach out and ask for help to avoid wasting your time! We're here to help and guide you!

# Challenges:

The trickiest part here is finding out what needs to get written in the `ScanData` function that you will be implementing. Looking at the existing spdx example will guide you a lot. The other challenge will be writing an xml parser to pull out the license information.

# Hints:

Use the spdx.go file as an example. Copy+paste it to pom.go and change all the relevant parts. Find a small example .pom file that you can use to test your code.

# Confidentiality:

Please remember that this is all public so don't include any private information that your employer or team mates wouldn't want shared.

Thank you!

**Comment by RaunakBose** [comment]
I am working on this.

**Comment by amznpurple** [comment]
>  Since I am not using a scanner I was wondering if I can use "pom scanner error" as an error message or should I say something else or is the scanner mentioned in the error message not talking about the scanner variable?

You should use the relevant error message. Either with `fmt.Errorf("some message")` or `errwrap.Wrapf(parent_error, "some new message")`. There is also `errwrap.Append` if you want to return multiple errors, but this is rare.

**Comment by RaunakBose** [comment]
>You should add an example file in examples/.pom that shows how this works.

Is there any specific place where I am not supposed to take the pom.xml files from? Or can they be from any where I find them?

**Comment by amznpurple** [comment]
> Is there any specific place where I am not supposed to take the pom.xml files from? Or can they be from any where I find them?

Up to you! Do what works best. Think of it this way:

In the open source world, pretend that it is entirely your idea for this patch. I'm not your manager requesting it. You are out there on your own and independent and your job is to propose something and convince me that your code and idea and design make sense!

Let's see what you come up with!

**Comment by RaunakBose** [comment]
Can I add the commands for POM in cmd/main.go? So I can try it out by running it on the command line.

**Comment by amznpurple** [comment]
This is done, we can close! \o/
