### ISSUE TITLE
Source headers

### ISSUE THREAD

**Issue by hyandell** [awslabs/yesiscan#2]
Source files should have headers for licensing.

// Copyright Amazon.com Inc or its affiliates
// Copyright The yesiscan project contributors
// SPDX-License-Identifier: Apache-2.0

**Comment by ovalba** [comment]
I agree, we need to correct this for the Open Source project.

**Comment by amznpurple** [comment]
I will add the SPDX ID shortly!

**Comment by amznpurple** [comment]
Done!
