### ISSUE TITLE
If we exclude a file, show that it was skipped

### ISSUE THREAD

**Issue by ajorg-aws** [awslabs/yesiscan#34]
There's discussion of skipping, for example, large .csv files, because they are probably data only and wouldn't contain license information. In such a case it's useful if the report can show that the file was skipped (and the summary note how many files were skipped).

Then if a file was skipped, it's useful to be able to go back and scan that file anyway without having to rescan the whole project. As a service, to be able to click on a link and fill in that file, or as a commandline, maybe to show what commandline options will tell yesiscan to scan just that file(s).

**Comment by amznpurple** [comment]
> There's discussion of skipping, for example, large .csv files, because they are probably data only and wouldn't contain license information. In such a case it's useful if the report can show that the file was skipped (and the summary note how many files were skipped).

I agree. We will add this. Thanks for the report.

> if a file was skipped, it's useful to be able to go back and scan that file anyway without having to rescan the whole project

This will take longer to do because it will depend on our caching layer being more powerful, but we will get there.

Thanks for the report!

**Comment by ovalba** [comment]
I love this feature, I think it's a blocker for Lite MVP. I would like to also document the "filter" for when files are excluded. Ex: I don't want the whole list of excluded files, I just want a subset based on a configurable criteria, like bigger than 300KB, certain filetypes.

**Comment by amznpurple** [comment]
This is implemented in git main. Thanks.
