### ISSUE TITLE
scan failed

### ISSUE THREAD

**Issue by vchhasatia** [awslabs/yesiscan#59]
main: failed: bufio.Scanner: token too long

**Comment by purpleidea** [comment]
I need info on what repo caused this please. If it's private, you can email it to me. Thanks.
Please also include the full invocation (which flags or backends) you used and the yesiscan version.

**Comment by vchhasatia** [comment]
Repo I was trying to scan - git.amazon.com/pkg/AKGamesJosephineUnity

I used 0.0.9_darwin amd64 on mac.

I scanned using askalono, bitbake, cran, pom and spdx. I excluded licenseclssifier, regexp and scancode.

From: James ***@***.***>
Reply-To: awslabs/yesiscan ***@***.***>
Date: Friday, October 14, 2022 at 11:06 AM
To: awslabs/yesiscan ***@***.***>
Cc: "Chhasatia, Viral" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/yesiscan] scan failed (Issue #59)


I need info on what repo caused this please. If it's private, you can email it to me. Thanks.
Please also include the full invocation (which flags or backends) you used and the yesiscan version.

**Comment by amznpurple** [comment]
Done. See other related issue.
