### ISSUE TITLE
Add license summary to output

### ISSUE THREAD

**Issue by tapdiego-amzn** [awslabs/yesiscan#7]
It would be great to get a summary of all licenses matched by each profile, lexicographically sorted, as the first item of the scan output. Here's what I have in mind:
```
main: license summary:
profile prof_1:
    * AGPL-3.0
    * GPL-3.0
profile prof_2:
    * Apache-2.0
    * MIT
```

**Comment by amznpurple** [comment]
I forgot to mention this earlier. This has been implemented and is in `git main` now. It will be available in the next released version. Thank you!
